---
title: "Final Project"
author: "abcd"
date: "today"
output: html_document
---

```{r include=FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(countrycode)
library(ggthemes)
library(ggpubr)
require(maps)
require(viridis)
options(scipen=100)

```


```{r include=FALSE}
salaries = read.csv("ds_salaries.csv")
```



#Top 3 jobs most appear
```{r echo=FALSE}
salaries %>% group_by(job_title) %>% count() %>% arrange(desc(n)) %>% head(3)
```


# Average Salary all over the world
```{r include=FALSE}
country_employee = salaries$employee_residence

salaries$country_employee = countrycode(country_employee, "iso2c", "country.name")

salaries %>% group_by(country_employee) %>% summarise(avg_salary = mean(salary_in_usd))

```

```{r fig.height=8, fig.width=15, warning=FALSE}
world_map <- map_data("world")
world_salaries <-salaries %>% group_by(country_employee) %>% summarise(avg_salary = mean(salary_in_usd))

# Changing the data manaually so that it matches

setdiff(world_salaries$country_employee, world_map$region)

world_salaries[world_salaries == "United States"] <- "USA"
world_salaries[world_salaries == "Czechia"] <- "Czech Republic"
world_salaries[world_salaries == "United Kingdom"] <- "UK"

countries_map <- right_join(world_salaries, world_map, by = c("country_employee"="region"))

ggplot(countries_map, aes(long, lat, group = group))+
  geom_polygon(aes(fill = avg_salary ), color = "white")+ scale_fill_viridis_c(option = "B")
```

# Compare between Remote ratio in each Company Size to their Average Salary their employees get paid
```{r, warning=FALSE, fig.height=5, fig.width=15}
salaries$remote_ratio[salaries$remote_ratio == '100'] <- '100%'
salaries$remote_ratio[salaries$remote_ratio == '50'] <- '50%'
salaries$remote_ratio[salaries$remote_ratio == '0'] <- '0%'

ggarrange (ggplot(salaries %>% group_by(company_size, remote_ratio)) + 
  geom_bar(mapping = aes(x = company_size, fill = remote_ratio), position = "dodge") +
    labs (title = "Ratio Remote", subtitle = "Company Size", y = "Number", x = "Company Size") + 
    scale_fill_discrete(name = "Remote Ratio"),

ggplot(salaries %>% group_by(company_size,remote_ratio) %>% summarize (avg_salary = mean(salary_in_usd))) + 
  geom_col(mapping = aes(x = company_size, y = avg_salary, fill = remote_ratio), position = "dodge")+
    labs (title = "Average Salary", subtitle = "Company Size", y = "Average Salary", x = "Company Size") + 
    scale_fill_discrete(name = "Remote Ratio"), ncol = 2, nrow =1 )
```


#the involution of exp_level via each year by salary
```{r}
salary_explevel = salaries %>% group_by(work_year,experience_level) %>% summarize(avg_salary = mean(salary))

salary_explevel$experience_level[salary_explevel$experience_level == 'EN'] <- 'Entry-level'
salary_explevel$experience_level[salary_explevel$experience_level == 'EX'] <- 'Executive-level'
salary_explevel$experience_level[salary_explevel$experience_level == 'MI'] <- 'Mid-level'
salary_explevel$experience_level[salary_explevel$experience_level == 'SE'] <- 'Senior-level'


ggplot(salary_explevel, aes(x = work_year, y = avg_salary,color = experience_level))+ geom_line() +
    labs (title = "Salary", subtitle = "Experience Level", y = "Average Salary", x = "Year") + 
    scale_colour_discrete(name = "Experience Level")
```
##I have no idea if company decrease man-power, increase salary